MLS = {'New York Red Bulls': 'RBNY', 'Charlotte FC': 'CLT', 'Sporting Kansas City': 'SKC',
       'San Jose Earthquakes': 'SJ',
       'Orlando City': 'ORL', 'FC Cincinnati': 'CIN', 'Nashville SC': 'NSH', 'Columbus Crew': 'CLB',
       'Atlanta United': 'ATL', 'Philadelphia Union': 'PHI', 'New England Revolution': 'NE',
       'St. Louis CITY SC': 'STL',
       'Seattle Sounders FC': 'SEA', 'FC Dallas': 'DAL', 'Los Angeles Football Club': 'LAFC',
       'Vancouver Whitecaps FC': 'VAN',
       'Houston Dynamo FC': 'HOU', 'Real Salt Lake': 'RSL', 'Inter Miami CF': 'MIA', 'New York City FC': 'NYC',
       'LA Galaxy': 'LA', 'D.C. United': 'DC', 'CF Montréal': 'MTL', 'Toronto FC': 'TOR', 'Chicago Fire FC': 'CHI',
       'Minnesota United': 'MIN', 'Austin FC': 'ATX', 'Colorado Rapids': 'COL', 'Portland Timbers': 'POR'}

LeaguesCup = {'New York Red Bulls': 'RBNY', 'Charlotte FC': 'CLT', 'Sporting Kansas City': 'SKC',
              'San Jose Earthquakes': 'SJ',
              'Orlando City': 'ORL', 'FC Cincinnati': 'CIN', 'Nashville SC': 'NSH', 'Columbus Crew': 'CLB',
              'Atlanta United': 'ATL', 'Philadelphia Union': 'PHI', 'New England Revolution': 'NE',
              'St. Louis CITY SC': 'STL',
              'Seattle Sounders FC': 'SEA', 'FC Dallas': 'DAL', 'Los Angeles Football Club': 'LAFC',
              'Vancouver Whitecaps FC': 'VAN',
              'Houston Dynamo FC': 'HOU', 'Real Salt Lake': 'RSL', 'Inter Miami CF': 'MIA', 'New York City FC': 'NYC',
              'LA Galaxy': 'LA', 'D.C. United': 'DC', 'CF Montréal': 'MTL', 'Toronto FC': 'TOR',
              'Chicago Fire FC': 'CHI',
              'Minnesota United': 'MIN', 'Austin FC': 'ATX', 'Colorado Rapids': 'COL', 'Portland Timbers': 'POR',
              'Mexican Dummy': 'MDU'}
